export const REGISTER_CLINIC_SUCCESS = 'REGISTER_CLINIC_SUCCESS';
export const REGISTER_CLINIC_PENDING = 'REGISTER_CLINIC_PENDING';
export const REGISTER_CLINIC_ERROR = 'REGISTER_CLINIC_ERROR';
export const REGISTER_RESET_ERROR = 'REGISTER_RESET_ERROR';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_PENDING = 'SIGN_IN_PENDING';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_RESET_ERROR = 'SIGN_IN_RESET_ERROR';