export const REGISTER_CLINIC_SUCCESS = 'REGISTER_CLINIC_SUCCESS';
export const REGISTER_CLINIC_PENDING = 'REGISTER_CLINIC_PENDING';
export const REGISTER_CLINIC_ERROR = 'REGISTER_CLINIC_ERROR';
export const REGISTER_RESET_ERROR = 'REGISTER_RESET_ERROR';