export const REGISTER_CLINIC_SUCCESS = 'REGISTER_CLINIC_SUCCESS';
export const REGISTER_CLINIC_PENDING = 'REGISTER_CLINIC_PENDING';
export const REGISTER_CLINIC_ERROR = 'REGISTER_CLINIC_ERROR';
export const REGISTER_RESET_ERROR = 'REGISTER_RESET_ERROR';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_PENDING = 'SIGN_IN_PENDING';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_RESET_ERROR = 'SIGN_IN_RESET_ERROR';

export const ACCOUNT_LOAD_SUCCESS = 'ACCOUNT_LOAD_SUCCESS';
export const ACCOUNT_LOAD_ERROR = 'ACCOUNT_LOAD_ERROR';

export const DOCTOR_CATEGORIES_LOAD_SUCCESS = 'DOCTOR_CATEGORIES_LOAD_SUCCESS';
export const DOCTOR_CATEGORIES_LOAD_ERROR = 'DOCTOR_CATEGORIES_LOAD_ERROR';

export const CREATE_DOCTOR_CATEGORY_SUCCESS = 'CREATE_DOCTOR_CATEGORY_SUCCESS';
export const CREATE_DOCTOR_CATEGORY_ERROR = 'CREATE_DOCTOR_CATEGORY_ERROR';
export const LOAD_DOCTOR_CATEGORY_SUCCESS = 'LOAD_DOCTOR_CATEGORY_SUCCESS';
export const LOAD_DOCTOR_CATEGORY_ERROR = 'LOAD_DOCTOR_CATEGORY_ERROR';

export const LOAD_DOCTORS_SUCCESS = 'LOAD_DOCTORS_SUCCESS';
export const LOAD_DOCTORS_ERROR = 'LOAD_DOCTORS_ERROR';